server:
  port: 9095
spring:
  zipkin:
    baseUrl: http://localhost:9411
spring.application.name: user-service
spring.cloud.stream:
  bindings:
    sendUpdateUser-out-0.destination: users-topic
stream:
  key: user-stream