version: '2.1'

services:
  elasticsearch:
    image: elasticsearch:7.11.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment: 
      - discovery.type=single-node
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
  zipkin:
    container_name: "zipkin"
    image: openzipkin/zipkin
    network_mode: bridge
    ports:
      - "9411:9411"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  ignite:
    image: "apacheignite/ignite:2.9.1"
    environment:
      CONFIG_URI: file:/ignite-config/ignite-config.xml
      IGNITE_QUIET: "false"      
    volumes:
    - ./ignite-config:/ignite-config:ro
    network_mode: host
    ports:
     - "11211:11211"
     - "47500-47509:47500-47509"
    restart: unless-stopped