server:
  port: 9095
spring:
  zipkin:
    baseUrl: http://localhost:9411
  application:
    name: product-service
stream:
  key: product-stream
aws:
  region: us-east-1
  dynamo:
    tableName: Product
    endpoint: http://localhost:443
