server:
  port: 9094
spring:
  zipkin:
    baseUrl: http://localhost:9411
  application:
    name: order-service
stream:
  key: order-stream
  user:
    key: user-stream
    group:
      name: order-user-group
  product:
    key: product-stream
    group:
      name: order-product-group